# app.py

import json
import os
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

# ── Rate Limiting ─────────────────────────────────────────────────────────────
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ── Groq client ───────────────────────────────────────────────────────────────
def get_groq_client():
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise ValueError("GROQ_API_KEY not set.")
    return Groq(api_key=api_key)

# ── Audit Log ─────────────────────────────────────────────────────────────────
LOG_FILE = "audit_log.json"

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)

def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

def append_log(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)

# ── Signal 1: LLM Classifier ──────────────────────────────────────────────────
def llm_signal(text: str) -> float:
    """
    Ask Groq to assess whether text is AI-generated.
    Returns float 0-1 (probability of AI authorship).
    """
    client = get_groq_client()
    prompt = f"""You are an AI authorship detector. Analyze the following text and 
estimate the probability (0.0 to 1.0) that it was generated by an AI tool rather 
than written by a human.

Consider: uniform tone, generic phrasing, overly structured argumentation, 
lack of personal voice, suspiciously perfect grammar.

Respond with ONLY a JSON object in this exact format:
{{"score": 0.85, "reasoning": "one sentence explanation"}}

Text to analyze:
\"\"\"{text}\"\"\"
"""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=100,
        temperature=0.1,
    )
    raw = response.choices[0].message.content.strip()
    parsed = json.loads(raw)
    return float(parsed["score"]), parsed.get("reasoning", "")

# ── Signal 2: Stylometric Heuristics ─────────────────────────────────────────
def stylometric_signal(text: str) -> float:
    """
    Measures statistical surface properties.
    Returns float 0-1 (probability of AI authorship).
    """
    import math
    import re

    sentences = re.split(r'[.!?]+', text.strip())
    sentences = [s.strip() for s in sentences if s.strip()]
    words = text.split()

    if len(sentences) < 2 or len(words) < 10:
        return 0.5  # not enough signal

    # 1. Sentence length variance (low variance = more AI-like)
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    # normalize: variance > 30 is very human, < 5 is very AI
    variance_score = max(0.0, min(1.0, 1.0 - (variance / 30.0)))

    # 2. Type-token ratio (low TTR = more AI-like)
    unique_words = set(w.lower().strip('.,!?";:') for w in words)
    ttr = len(unique_words) / len(words)
    # TTR < 0.5 is AI-like, > 0.8 is human-like
    ttr_score = max(0.0, min(1.0, 1.0 - ((ttr - 0.5) / 0.3)))

    # 3. Punctuation diversity (low diversity = more AI-like)
    punct_types = set(c for c in text if c in '!?;:—–…()\'\"')
    punct_score = max(0.0, min(1.0, 1.0 - (len(punct_types) / 6.0)))

    combined = (variance_score + ttr_score + punct_score) / 3.0
    return round(combined, 3)

# ── Confidence Scoring ────────────────────────────────────────────────────────
def combine_scores(llm_score: float, stylo_score: float) -> float:
    return round(0.6 * llm_score + 0.4 * stylo_score, 3)

# ── Transparency Label ────────────────────────────────────────────────────────
def get_label(confidence: float) -> str:
    if confidence >= 0.75:
        return (
            "⚠️ AI-Generated Content Detected\n"
            "Our system found strong indicators that this content was likely generated "
            "by an AI tool. This does not mean the work has no value — but readers "
            "deserve to know. Confidence: High. If you wrote this yourself, you can "
            "file an appeal below."
        )
    elif confidence >= 0.40:
        return (
            "🔍 Authorship Uncertain\n"
            "Our system found mixed signals about whether this content was written by "
            "a human or generated by AI. We're not confident enough to make a clear "
            "call. Confidence: Low-to-moderate. This content is being shown as-is. "
            "If you're the author, you can add context or file an appeal below."
        )
    else:
        return (
            "✅ Likely Human-Written\n"
            "Our system found no strong indicators of AI generation. This content "
            "appears to have been written by its credited author. Confidence: High."
        )

def get_attribution(confidence: float) -> str:
    if confidence >= 0.75:
        return "likely_ai"
    elif confidence >= 0.40:
        return "uncertain"
    else:
        return "likely_human"

# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data or not data.get("text") or not data.get("creator_id"):
        return jsonify({"error": "Missing required fields: text, creator_id"}), 400

    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())

    # Run both signals
    llm_score, llm_reasoning = llm_signal(text)
    stylo_score = stylometric_signal(text)
    confidence = combine_scores(llm_score, stylo_score)
    attribution = get_attribution(confidence)
    label = get_label(confidence)

    # Write to audit log
    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "llm_reasoning": llm_reasoning,
        "stylo_score": stylo_score,
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None,
    }
    append_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "label": label,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or not data.get("content_id") or not data.get("creator_reasoning"):
        return jsonify({"error": "Missing required fields: content_id, creator_reasoning"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    entries = read_log()
    updated = False
    for entry in entries:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = reasoning
            entry["appeal_timestamp"] = datetime.now(timezone.utc).isoformat()
            updated = True
            break

    if not updated:
        return jsonify({"error": "content_id not found"}), 404

    write_log(entries)
    return jsonify({
        "status": "under_review",
        "message": "Appeal received. Your content is now under review."
    })


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    return jsonify({"entries": entries[-20:]})  # return last 20


if __name__ == "__main__":
    app.run(debug=True, port=5001)